language: java
jdk:
  - openjdk11

branches:
  only:
    - main

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

notifications:
  email:
    recipients:
      - kkam2ya@gmail.com

before_deploy:
  - zip -r project-e-seok-webservice *
  - mkdir -p deploy
  - mv project-e-seok-webservice.zip deploy/project-e-seok-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: project-e-seok-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: project-e-seok-build
    key: project-e-seok-webservice.zip
    bundle_type: zip
    application: project-e-seok-webservice
    deployment_group: project-e-seok-webservice-group
    region: ap-northeast-2
    wait-until-deployed: true