spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: none

  session:
    store-type: jdbc

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: true
    enabled: true

