spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: none
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5

