spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  session:
    store-type: jdbc

  thymeleaf:
    prefix: classpath:templates/thymeleaf/
    check-template-location: true
    suffix: .html
    mode: HTML
    cache: true

