spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project_e_seok
    username: root
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    prefix: classpath:templates/thymeleaf/
    check-template-location: false
    suffix: .html
    mode: HTML
    cache: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

