spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: common

  thymeleaf:
    prefix: templates/thymeleaf
    check-template-location: true
    suffix: .html
    mode: HTML
    cache: true